name: Remote Dispatch Action Responder
 
on: [repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Event Information
      run: |
        echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
